import Foundation

public enum RemoveStrategy: Sendable {
    case contents
    case item
    case simulatorData
    case scanOnlyContents
    case desktopDevCaches
}

public enum CleanupAvailability: Sendable {
    case cleanable
    case itemized
    case scanOnly
}

public struct CleanupPath: Hashable, Sendable {
    public let rawValue: String
    public let removeStrategy: RemoveStrategy

    public init(rawValue: String, removeStrategy: RemoveStrategy) {
        self.rawValue = rawValue
        self.removeStrategy = removeStrategy
    }

    public var expandedPath: String {
        (rawValue as NSString).expandingTildeInPath
    }

    public var displayPath: String {
        rawValue
    }
}

public struct CleanupCategory: Hashable, Sendable {
    public let id: String
    public let name: String
    public let description: String
    public let paths: [CleanupPath]
    public let requiresFullDiskAccess: Bool
    public let cleanupAvailability: CleanupAvailability

    public init(
        id: String,
        name: String,
        description: String,
        paths: [CleanupPath],
        requiresFullDiskAccess: Bool = false,
        cleanupAvailability: CleanupAvailability = .cleanable
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.paths = paths
        self.requiresFullDiskAccess = requiresFullDiskAccess
        self.cleanupAvailability = cleanupAvailability
    }
}

public enum CleanupCatalogError: Error, LocalizedError, Sendable {
    case unknownCategory(String)

    public var errorDescription: String? {
        switch self {
        case .unknownCategory(let token):
            return "Unknown category: \(token)"
        }
    }
}

public enum CleanupCatalog {
    public static let categories: [CleanupCategory] = [
        CleanupCategory(
            id: "caches",
            name: "Caches",
            description: "App and system cache files under the user Library",
            paths: [
                CleanupPath(rawValue: "~/Library/Caches", removeStrategy: .contents),
            ]
        ),
        CleanupCategory(
            id: "logs",
            name: "Logs",
            description: "User and app log files",
            paths: [
                CleanupPath(rawValue: "~/Library/Logs", removeStrategy: .contents),
            ]
        ),
        CleanupCategory(
            id: "xcode-derived-data",
            name: "Xcode DerivedData",
            description: "Build intermediates generated by Xcode",
            paths: [
                CleanupPath(rawValue: "~/Library/Developer/Xcode/DerivedData", removeStrategy: .contents),
            ]
        ),
        CleanupCategory(
            id: "ios-device-support",
            name: "iOS Device Support",
            description: "Old device support images downloaded by Xcode",
            paths: [
                CleanupPath(rawValue: "~/Library/Developer/Xcode/iOS DeviceSupport", removeStrategy: .contents),
            ]
        ),
        CleanupCategory(
            id: "simulator-caches",
            name: "Simulator Caches",
            description: "CoreSimulator cache files",
            paths: [
                CleanupPath(rawValue: "~/Library/Developer/CoreSimulator/Caches", removeStrategy: .contents),
            ]
        ),
        CleanupCategory(
            id: "simulator-devices",
            name: "Simulator Devices",
            description: "App data, media, and install state inside iOS simulators",
            paths: [
                CleanupPath(rawValue: "~/Library/Developer/CoreSimulator/Devices", removeStrategy: .simulatorData),
            ]
        ),
        CleanupCategory(
            id: "mail-downloads",
            name: "Mail Downloads",
            description: "Downloaded Mail attachment files stored in a protected Library container",
            paths: [
                CleanupPath(
                    rawValue: "~/Library/Containers/com.apple.mail/Data/Library/Mail Downloads",
                    removeStrategy: .contents
                ),
            ],
            requiresFullDiskAccess: true
        ),
        CleanupCategory(
            id: "desktop-dev-caches",
            name: "Old Dev Caches (Desktop)",
            description: "Developer build artifacts under Desktop that have been stale for 30+ days",
            paths: [
                CleanupPath(
                    rawValue: "~/Desktop",
                    removeStrategy: .desktopDevCaches
                ),
            ]
        ),
        CleanupCategory(
            id: "mobile-backups",
            name: "Device Backups",
            description: "Local iPhone and iPad backups stored by Finder",
            paths: [
                CleanupPath(
                    rawValue: "~/Library/Application Support/MobileSync/Backup",
                    removeStrategy: .scanOnlyContents
                ),
            ],
            requiresFullDiskAccess: true,
            cleanupAvailability: .itemized
        ),
        CleanupCategory(
            id: "trash",
            name: "Trash",
            description: "Items currently in the user Trash",
            paths: [
                CleanupPath(rawValue: "~/.Trash", removeStrategy: .contents),
            ]
        ),
    ]

    private static let categoriesByID = Dictionary(uniqueKeysWithValues: categories.map { ($0.id, $0) })

    private static let aliases = [
        "cache": "caches",
        "caches": "caches",
        "log": "logs",
        "logs": "logs",
        "derived-data": "xcode-derived-data",
        "xcode-derived-data": "xcode-derived-data",
        "device-support": "ios-device-support",
        "ios-device-support": "ios-device-support",
        "mail": "mail-downloads",
        "mail-downloads": "mail-downloads",
        "mail-download": "mail-downloads",
        "desktop-dev-caches": "desktop-dev-caches",
        "desktop-caches": "desktop-dev-caches",
        "dev-caches": "desktop-dev-caches",
        "old-dev-caches": "desktop-dev-caches",
        "tauri": "desktop-dev-caches",
        "tauri-target": "desktop-dev-caches",
        "rust-target": "desktop-dev-caches",
        "backup": "mobile-backups",
        "backups": "mobile-backups",
        "mobile-backup": "mobile-backups",
        "mobile-backups": "mobile-backups",
        "simulator": "simulator-devices",
        "simulators": "simulator-devices",
        "simulator-data": "simulator-devices",
        "simulator-devices": "simulator-devices",
        "simulator-caches": "simulator-caches",
        "trash": "trash",
        "bin": "trash",
    ]

    public static func resolve(_ tokens: [String]) throws -> [CleanupCategory] {
        if tokens.isEmpty || tokens.map({ $0.lowercased() }).contains("all") {
            return categories
        }

        var selected: [CleanupCategory] = []
        var seen: Set<String> = []

        for token in tokens {
            let key = token.lowercased()
            guard let categoryID = aliases[key],
                  let category = categoriesByID[categoryID] else {
                throw CleanupCatalogError.unknownCategory(token)
            }

            if seen.insert(categoryID).inserted {
                selected.append(category)
            }
        }

        return selected
    }
}
